### ISSUE TITLE
MAROQQO @ Drupal should be added to both social link sections

### ISSUE THREAD

**Issue by diqidoq** [diqidoq/maroqqo-vcard#11]
MAROQQO @ Drupal should be added to both social link sections including a Drupal logo and a link to the MAROQQO Drupal service provider page @ drupal.org. The same with GitHub (additional)

**Comment by diqidoq** [comment]
@ocbtec thanks!

**Comment by diqidoq** [comment]
[Line 554, 590,1155, 1201](https://github.com/diqidoq/maroqqo-vcard/commit/755f3cf8c1fedbe6e2e19da5f6559b3c73aa7c60): This changes are NOT part of this issue. [Line 554, 590](https://github.com/diqidoq/maroqqo-vcard/commit/755f3cf8c1fedbe6e2e19da5f6559b3c73aa7c60): These lines are part of issue  #14. Please add code comment to this code lines referring to here. But we keep it in to prevent revert history editing. Please split tasks by issues next time. 

[Line 1155, 1201](https://github.com/diqidoq/maroqqo-vcard/commit/755f3cf8c1fedbe6e2e19da5f6559b3c73aa7c60): other changes not listed in the issue queue yet.

**Comment by ocbtec** [comment]
[Line 1155, 1201](https://github.com/diqidoq/maroqqo-vcard/commit/755f3cf8c1fedbe6e2e19da5f6559b3c73aa7c60): Changed Project names.
